apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: dask-worker
  labels:
    app: dask-worker
spec:
  selector:
    matchLabels:
      app: dask-worker
  replicas: 10
  template:
    metadata:
      labels:
        app: dask-worker
    spec:
      containers:
      - name: dask-worker
        image: gcr.io/tmbmicro/docker-pytorch:latest
        command: ["dask-worker"]
        args: ["--worker-port", "18786", "--nanny-port", "18787", "dask-scheduler:8786"]
        ports:
        - containerPort: 18786
        - containerPort: 18787
