apiVersion: v1
kind: Service
metadata:
  name: jupyter
spec:
  type: LoadBalancer
  selector:
    app: jupyter
  ports:
  - name: http
    port: 80
    targetPort: 8888
    protocol: TCP
  - name: www-scheduler
    port: 8787
    targetPort: 8787
    protocol: TCP
  - name: www-diagnostic
    port: 8788
    targetPort: 8788
    protocol: TCP
  - name: www-workers
    port: 8789
    targetPort: 8789
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler
spec:
  selector:
    app: jupyter
  ports:
  - port: 8786
    protocol: TCP
