#!/bin/bash -xe

PROJECT=tmbmicro

echo
echo "pushing docker-pytorch to registry"
echo

make docker-pytorch
docker tag docker-pytorch gcr.io/${PROJECT}/docker-pytorch
gcloud docker -- push gcr.io/${PROJECT}/docker-pytorch

for fname in gce-*.yaml; do
    sed -i "s|gcr.io/[a-z]*/docker-pytorch|gcr.io/${PROJECT}/docker-pytorch|g" $fname
done

echo
echo "starting up Kubernetes cluster on GKE"
echo

gcloud config set project ${PROJECT}
gcloud config set compute/zone us-west1-a
gcloud container clusters create tmbcluster
gcloud container clusters get-credentials tmbcluster

echo
echo "running Jupyter and Dask Workers in cluster"
echo

kubectl apply -f ./gce-service.yaml
kubectl apply -f ./gce-jupyter.yaml
kubectl apply -f ./gce-worker.yaml

echo
echo run ./gce-monitor to view progress
echo change number of workers by editing gce-worker.yaml and reapplying
echo
