#!/bin/bash

workdef=/work
datadef=/data1
test -d /nfs/work/. && workdef=/nfs/work
work=${workdir:-$workdef}
data=${datadir:-$datadef}
echo /work=$work

docker kill docker-pytorch 2>&1 || true
docker rm docker-pytorch 2>&1 || true

nvidia-docker run --name docker-pytorch \
    -t -i ${flags:-"-d"} \
    --init \
    -e "HOSTNAME=$(hostname)" \
    -v /etc/ssh:/etc/ssh \
    -v $work:/work \
    -v $data:/data \
    -p 15922:5900 \
    -p 15022:22 \
    -p 15888:8888 \
    --restart always \
    --cap-add SYS_ADMIN \
    --device /dev/fuse \
    --security-opt apparmor:unconfined \
    docker-pytorch
